name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Actúa en pushes a la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Revisa el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura Docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construye y sube la imagen a Docker Hub
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-new-app .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-new-app

    # Opcional: Implementación
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
        docker pull ${{ secrets.DOCKER_USERNAME }}/my-new-app
        docker stop my-node-app || true
        docker run -d --name my-new-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/my-new-app
        EOF
